{
  "version": 3,
  "createdUtc": "2026-09-08T10:51:27.5994491Z",
  "start": {
    "areaSid": "Celeste/5-MirrorTemple",
    "areaMode": "Normal",
    "level": "d-01",
    "respawnX": 3584,
    "respawnY": 1424
  },
  "inputs": [
    "44",
    "1,Z",
    "7,R,D,J,Z",
    "48,R,D,J",
    "2,D,J",
    "11,D,J,X",
    "10,D,X",
    "8,D",
    "1,R,D,J",
    "12,R,J",
    "4,L,G",
    "12,L,J,G",
    "6,L,K,G",
    "4,L,G",
    "1,L",
    "12",
    "1,R,U",
    "8,R,U,X",
    "1,R,X",
    "2,R",
    "6",
    "34,D",
    "1,D,G",
    "8,R,D,Z,G",
    "5,R,D,G",
    "1,R,D,J,G",
    "4,R,D,J,Z,G",
    "3,R,D,Z,G",
    "5,R,D,G",
    "1,R,D,J,G",
    "3,R,J,G",
    "10,R,G",
    "11,R,J,G",
    "27,J,G",
    "8,G",
    "3,D,G",
    "13,D,X",
    "9,D",
    "3,R,D",
    "10,R,D,X",
    "3,R,D",
    "3,R,D,J",
    "9,R,D",
    "10,R,D,X",
    "1,R",
    "4,R,J",
    "8,R,J,Z",
    "1,R,Z",
    "3,R,D,Z",
    "6,D",
    "27,L,D",
    "16,D",
    "1,L,D",
    "4,L",
    "13,L,J",
    "1,L,D,J",
    "6,L,D,J,X",
    "4,L,D,X",
    "1,L",
    "4,L,J",
    "8,L,J,X",
    "1,R,X",
    "1,R,D,X",
    "27,R,D",
    "2,L,D,Z",
    "4,L,D,J,Z",
    "1,L,D,Z",
    "12,L,D",
    "2,L,D,Z",
    "5,L,D,J,Z",
    "1,L,D,Z",
    "12,L,D",
    "1,L,D,Z",
    "10,L,D,J,Z",
    "1,L,D",
    "5,R,D",
    "7,D"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"d-01\" Time=\"0\" StartedFromBeginning=\"false\" Deaths=\"0\" Dashes=\"0\" DashesAtLevelStart=\"0\" DeathsInCurrentLevel=\"0\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"5\" Mode=\"Normal\" SID=\"Celeste/5-MirrorTemple\" />\r\n  <RespawnPoint>\r\n    <X>3584</X>\r\n    <Y>1424</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/music/lvl5/mirror\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"0\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"0\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience Event=\"event:/env/amb/05_interior_main\">\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>1</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>true</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags />\r\n  <LevelFlags>\r\n    <string>d-01</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters />\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"5\" Cassette=\"false\" SID=\"Celeste/5-MirrorTemple\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"272\" TimePlayed=\"38982700000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"true\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>d-00</string>\r\n          <string>e-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"313\" TimePlayed=\"13163270000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"true\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-00</string>\r\n          <string>d-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>d-01</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}