{
  "version": 3,
  "createdUtc": "2026-08-03T11:13:27.2044868Z",
  "start": {
    "areaSid": "Celeste/7-Summit",
    "areaMode": "Normal",
    "level": "d-11",
    "respawnX": 14488,
    "respawnY": -7464
  },
  "inputs": [
    "36",
    "1,X",
    "11,R,X",
    "1,R",
    "1,R,U",
    "11,R,U,X",
    "1,R,X",
    "2,R",
    "10,R,X",
    "4,R,D,X",
    "22,R,D",
    "21,D",
    "33",
    "1,U",
    "2,L,U",
    "12,L,U,X",
    "3,L,U",
    "1,U",
    "11,U,X",
    "7,U",
    "1,U,J",
    "13,R,U,J",
    "1,U,J",
    "3,L,U,J",
    "1,L,J",
    "27,L",
    "13,L,X",
    "3,L",
    "2,L,D",
    "10,L,D,X",
    "8,L,D",
    "3,L,D,X",
    "8,L,D,J,X",
    "3,L,D,J",
    "13,R,D,J",
    "50,R,D",
    "2,R",
    "10,R,X",
    "4,R",
    "13,R,X",
    "29,R",
    "21",
    "1,Z",
    "1,J,Z",
    "7,R,J,Z",
    "1,R,Z",
    "3,R",
    "43,L",
    "9,L,X",
    "8,L",
    "11,L,X",
    "24,L",
    "211",
    "1,S",
    "1,D,S,O",
    "2,S",
    "138"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"d-11\" Time=\"180200000\" StartedFromBeginning=\"false\" Deaths=\"2\" Dashes=\"3\" DashesAtLevelStart=\"3\" DeathsInCurrentLevel=\"2\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"7\" Mode=\"Normal\" SID=\"Celeste/7-Summit\" />\r\n  <RespawnPoint>\r\n    <X>14488</X>\r\n    <Y>-7464</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/music/lvl7/main\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience>\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>2</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>false</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags />\r\n  <LevelFlags>\r\n    <string>d-11</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters />\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"7\" Cassette=\"true\" SID=\"Celeste/7-Summit\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"485\" TimePlayed=\"62719460000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"true\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-00</string>\r\n          <string>d-00</string>\r\n          <string>e-00b</string>\r\n          <string>f-00</string>\r\n          <string>g-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"208\" TimePlayed=\"61265110000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-01</string>\r\n          <string>d-00</string>\r\n          <string>e-00</string>\r\n          <string>f-00</string>\r\n          <string>g-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>d-11</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}