{
  "version": 3,
  "createdUtc": "2026-08-03T10:27:40.5824036Z",
  "start": {
    "areaSid": "Celeste/7-Summit",
    "areaMode": "Normal",
    "level": "a-06",
    "respawnX": 3087,
    "respawnY": -1056
  },
  "inputs": [
    "10",
    "7,U",
    "31,R,U",
    "9,R,U,X",
    "2,R,X",
    "4,R",
    "14,R,X",
    "1,R",
    "44,R,U",
    "11,R,U,X",
    "1,R,U",
    "2,L,U",
    "19,L",
    "10,L,X",
    "1,L,D,X",
    "29,L,D",
    "1,L",
    "13,L,X",
    "16,L",
    "6,L,U",
    "28,U",
    "11,U,X",
    "2,U",
    "1,L,U",
    "11,L,U,X",
    "1,R,X",
    "2,R",
    "12,R,X",
    "1,R,D",
    "14,R,D,X",
    "29,R,D",
    "1,D",
    "138",
    "2,S",
    "1,D,S,O",
    "3,S",
    "137"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"a-06\" Time=\"907630000\" StartedFromBeginning=\"false\" Deaths=\"6\" Dashes=\"11\" DashesAtLevelStart=\"11\" DeathsInCurrentLevel=\"2\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"7\" Mode=\"Normal\" SID=\"Celeste/7-Summit\" />\r\n  <RespawnPoint>\r\n    <X>3087</X>\r\n    <Y>-1056</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/music/lvl7/main\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n        <MEP Key=\"progress\" Value=\"1\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience Event=\"event:/env/amb/01_main\">\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>2</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>false</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags>\r\n    <string>beginswap_-1</string>\r\n    <string>CelesteTAS_TAS_Was_Run</string>\r\n    <string>StopFastRestartFlag</string>\r\n    <string>SpeedrunTool_SavedSate</string>\r\n  </Flags>\r\n  <LevelFlags>\r\n    <string>a-00-intro</string>\r\n    <string>a-06</string>\r\n    <string>b-00</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters />\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"7\" Cassette=\"true\" SID=\"Celeste/7-Summit\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"353\" TimePlayed=\"38348090000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"true\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-00</string>\r\n          <string>d-00</string>\r\n          <string>e-00b</string>\r\n          <string>f-00</string>\r\n          <string>g-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"208\" TimePlayed=\"61265110000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-01</string>\r\n          <string>d-00</string>\r\n          <string>e-00</string>\r\n          <string>f-00</string>\r\n          <string>g-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>b-00</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}