{
  "version": 3,
  "createdUtc": "2026-08-03T11:30:23.1899133Z",
  "start": {
    "areaSid": "Celeste/7-Summit",
    "areaMode": "Normal",
    "level": "c-09",
    "respawnX": 10081,
    "respawnY": -6248
  },
  "inputs": [
    "37",
    "11,L",
    "14,L,X",
    "11,L",
    "1,L,X",
    "12,U,X",
    "4,L",
    "14,L,X",
    "1,L",
    "23,L,D",
    "2,L",
    "14,L,X",
    "4,L",
    "1,L,U",
    "14,U,X",
    "2,U",
    "30,R,U",
    "12,R,U,X",
    "2,R,U",
    "1,R",
    "14,R,X",
    "4,R",
    "8",
    "1,U",
    "15,U,X",
    "25,U,J",
    "3,U",
    "177",
    "4,S",
    "1,D,S,O",
    "2,S",
    "138"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"c-09\" Time=\"4458760000\" StartedFromBeginning=\"false\" Deaths=\"78\" Dashes=\"33\" DashesAtLevelStart=\"33\" DeathsInCurrentLevel=\"1\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"7\" Mode=\"Normal\" SID=\"Celeste/7-Summit\" />\r\n  <RespawnPoint>\r\n    <X>10081</X>\r\n    <Y>-6248</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/music/lvl7/main\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience>\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>2</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>false</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags>\r\n    <string>StopFastRestartFlag</string>\r\n    <string>SpeedrunTool_SavedSate</string>\r\n  </Flags>\r\n  <LevelFlags>\r\n    <string>e-04</string>\r\n    <string>e-05</string>\r\n    <string>e-06</string>\r\n    <string>e-07</string>\r\n    <string>c-09</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters />\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"7\" Cassette=\"true\" SID=\"Celeste/7-Summit\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"500\" TimePlayed=\"67036610000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"true\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-00</string>\r\n          <string>d-00</string>\r\n          <string>e-00b</string>\r\n          <string>f-00</string>\r\n          <string>g-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"208\" TimePlayed=\"61265110000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-01</string>\r\n          <string>d-00</string>\r\n          <string>e-00</string>\r\n          <string>f-00</string>\r\n          <string>g-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>c-09</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}