{
  "version": 3,
  "createdUtc": "2026-08-03T11:34:08.1736852Z",
  "start": {
    "areaSid": "Celeste/7-Summit",
    "areaMode": "Normal",
    "level": "b-09",
    "respawnX": 6011,
    "respawnY": -3221
  },
  "inputs": [
    "72,L",
    "12,L,X",
    "6,L",
    "2,L,G",
    "8,L,U,G",
    "12,L,U,Z,G",
    "2,L,U,G",
    "2,L,U,J,G",
    "10,L,J,G",
    "2,L,G",
    "7,L,D,G",
    "9,D",
    "14,L,D",
    "2,D",
    "4",
    "31,U",
    "18,L,U",
    "3,U",
    "13,U,X",
    "3,U",
    "2",
    "1,L",
    "10,L,X",
    "2,L,U",
    "1,U",
    "1,U,J",
    "9,U,J,X",
    "2,U,X",
    "2,U",
    "1",
    "1,R",
    "10,R,X",
    "2,R",
    "4,R,J",
    "2,R,U,J",
    "3,U",
    "9,U,J",
    "11,U,J,X",
    "2,U,J",
    "1,U,J,G",
    "19,R,U,J,X,G",
    "4,R,U,J,G",
    "4,R,U,G",
    "2,R,U,X,G",
    "11,U,X,G",
    "3,U,G",
    "1,U,X,G",
    "14,R,U,X,G",
    "7,R,U,G",
    "1,U",
    "212",
    "2,S",
    "1,D,S,O",
    "2,S",
    "138"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"b-09\" Time=\"515270000\" StartedFromBeginning=\"false\" Deaths=\"9\" Dashes=\"0\" DashesAtLevelStart=\"0\" DeathsInCurrentLevel=\"9\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"7\" Mode=\"Normal\" SID=\"Celeste/7-Summit\" />\r\n  <RespawnPoint>\r\n    <X>6011</X>\r\n    <Y>-3221.5</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/music/lvl7/main\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience>\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>2</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>false</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags>\r\n    <string>beginswap_-1</string>\r\n  </Flags>\r\n  <LevelFlags>\r\n    <string>a-00-intro</string>\r\n    <string>b-09</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters />\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"7\" Cassette=\"false\" SID=\"Celeste/7-Summit\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>b-09</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}