{
  "version": 3,
  "createdUtc": "2026-08-03T11:43:55.8582603Z",
  "start": {
    "areaSid": "Celeste/7-Summit",
    "areaMode": "Normal",
    "level": "e-13",
    "respawnX": 20265,
    "respawnY": -10088
  },
  "inputs": [
    "92,U",
    "11,U,X",
    "3,U",
    "12,R,U,X",
    "2,L,U",
    "34,L",
    "1,L,D",
    "13,L,D,X",
    "4,L,D",
    "12,L,Z",
    "3,L",
    "12,L,X",
    "3,L",
    "1,L,X",
    "14,L,D,X",
    "4,L,D",
    "1,L,D,X",
    "27,L,X",
    "2,L",
    "31,L,U",
    "12,L,U,X",
    "3,R,U,X",
    "31,R,U",
    "13,R,U,X",
    "3,R",
    "14,R,Z",
    "6,R",
    "11,R,Z",
    "2,R",
    "30,R,J",
    "3,R,U",
    "31,U",
    "12,U,X",
    "5,U",
    "14,L,U,X",
    "8,L,U",
    "26,L",
    "14,L,X",
    "3,L",
    "2,L,D",
    "1,D",
    "11,D,X",
    "5,D",
    "1,R,D",
    "11,R,D,X",
    "2,L,D,X",
    "2,L,D",
    "2,L",
    "14,L,X",
    "12,L",
    "30,L,Z",
    "2,L,U,Z",
    "1,L,U",
    "32,U",
    "11,U,X",
    "3,R,U,X",
    "15,R,U",
    "34,R",
    "9,R,Z",
    "3,R",
    "13,R,X",
    "12,R",
    "192",
    "2,S",
    "1,D,S,O",
    "3,S",
    "137"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"e-13\" Time=\"530910000\" StartedFromBeginning=\"false\" Deaths=\"3\" Dashes=\"16\" DashesAtLevelStart=\"16\" DeathsInCurrentLevel=\"1\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"7\" Mode=\"Normal\" SID=\"Celeste/7-Summit\" />\r\n  <RespawnPoint>\r\n    <X>20265.5</X>\r\n    <Y>-10088.5</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/music/lvl7/main\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n        <MEP Key=\"progress\" Value=\"4\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience Event=\"event:/env/amb/04_main\">\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>2</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>false</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags>\r\n    <string>CelesteTAS_TAS_Was_Run</string>\r\n    <string>SpeedrunTool_Reset_unpauseTimer</string>\r\n    <string>StopFastRestartFlag</string>\r\n    <string>SpeedrunTool_SavedSate</string>\r\n  </Flags>\r\n  <LevelFlags>\r\n    <string>d-11</string>\r\n    <string>e-00b</string>\r\n    <string>e-07</string>\r\n    <string>e-13</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters />\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"7\" Cassette=\"true\" SID=\"Celeste/7-Summit\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"348\" TimePlayed=\"36146930000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"true\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-00</string>\r\n          <string>d-00</string>\r\n          <string>e-00b</string>\r\n          <string>f-00</string>\r\n          <string>g-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"208\" TimePlayed=\"61265110000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-01</string>\r\n          <string>d-00</string>\r\n          <string>e-00</string>\r\n          <string>f-00</string>\r\n          <string>g-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>e-13</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}