{
  "version": 3,
  "createdUtc": "2026-08-03T10:49:50.3683283Z",
  "start": {
    "areaSid": "Celeste/7-Summit",
    "areaMode": "Normal",
    "level": "f-11",
    "respawnX": 25517,
    "respawnY": -11752
  },
  "inputs": [
    "37,L",
    "12,L,X",
    "3,R,X",
    "33,R",
    "10,R,X",
    "6,R",
    "21,R,X",
    "9,R",
    "42,U",
    "12,U,X",
    "2,U",
    "1,U,G",
    "1,L,G",
    "11,L,X,G",
    "3,L,G",
    "1,L,X,G",
    "12,L,D,X,G",
    "1,L,D,G",
    "1,L,D,J,G",
    "23,L,J,G",
    "2,L,U,J,G",
    "8,L,U,J,X,G",
    "6,L,U,X,G",
    "2,L,U,G",
    "2,L,U,J,G",
    "7,U,J,G",
    "9,U,J,X,G",
    "3,U,X,G",
    "2,R,U,G",
    "2,R,U,J,G",
    "51,R,J,G",
    "33,R,G",
    "11,R,U,G",
    "5,R,U,J,H",
    "1,R,U,K,H",
    "19,R,U,J,H",
    "3,L,U,J,H",
    "1,L,U,H",
    "48,L,H",
    "9,L,J,H",
    "9,L,K,H",
    "6,L,J,H",
    "3,L,H",
    "10,L",
    "18,L,J",
    "9,L,J,X",
    "5,X",
    "8",
    "8,J",
    "15,R,J",
    "4,R",
    "10,R,J",
    "10,R,K",
    "3,L,K,G",
    "12,L,J,G",
    "3,L,G",
    "10,G",
    "8,R,J,G",
    "6,R,G",
    "1,R",
    "36",
    "2,L",
    "9,L,J",
    "6,J",
    "1,U,J",
    "8,U,J,X",
    "5,U,J",
    "8,U,J,X",
    "5,U,J",
    "18,U,J,X",
    "26,U,J",
    "8,U",
    "175",
    "2,S",
    "1,D,S,O",
    "1,S",
    "139"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"f-11\" Time=\"2960720000\" StartedFromBeginning=\"false\" Deaths=\"18\" Dashes=\"16\" DashesAtLevelStart=\"16\" DeathsInCurrentLevel=\"4\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"7\" Mode=\"Normal\" SID=\"Celeste/7-Summit\" />\r\n  <RespawnPoint>\r\n    <X>25517.2</X>\r\n    <Y>-11752</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/music/lvl7/main\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience>\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>2</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>false</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags>\r\n    <string>StopFastRestartFlag</string>\r\n    <string>SpeedrunTool_SavedSate</string>\r\n  </Flags>\r\n  <LevelFlags>\r\n    <string>f-10b</string>\r\n    <string>f-11</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters />\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"7\" Cassette=\"true\" SID=\"Celeste/7-Summit\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"407\" TimePlayed=\"47906000000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"true\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-00</string>\r\n          <string>d-00</string>\r\n          <string>e-00b</string>\r\n          <string>f-00</string>\r\n          <string>g-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"208\" TimePlayed=\"61265110000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-01</string>\r\n          <string>d-00</string>\r\n          <string>e-00</string>\r\n          <string>f-00</string>\r\n          <string>g-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>f-11</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}