{
  "version": 3,
  "createdUtc": "2026-08-08T13:04:22.3877803Z",
  "start": {
    "areaSid": "Celeste/6-Reflection",
    "areaMode": "BSide",
    "level": "d-00",
    "respawnX": 10968,
    "respawnY": 4960
  },
  "inputs": [
    "43",
    "3,X",
    "1,R,X",
    "6,R,D,X",
    "2,R,D",
    "1,R",
    "1,R,J",
    "2,R,J,X",
    "7,R,U,J,X",
    "4,R,U,X",
    "1,R",
    "3,L",
    "27,L,D",
    "1,D",
    "11",
    "2,L,D",
    "8,L,D,Z",
    "1,D,Z",
    "1,R,Z",
    "2,R",
    "16,R,J",
    "1,L,J,X",
    "7,L,U,J,X",
    "2,L,X",
    "21,L",
    "5,L,G",
    "7,G",
    "4,D,G",
    "29,G",
    "8,R,G",
    "8,R,J,G",
    "8,R,G",
    "3,R",
    "15,R,D",
    "1,D"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"d-00\" Time=\"750210000\" StartedFromBeginning=\"false\" Deaths=\"34\" Dashes=\"0\" DashesAtLevelStart=\"0\" DeathsInCurrentLevel=\"31\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" ColorGrade=\"reflection\" LightingAlphaAdd=\"0.06\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"6\" Mode=\"BSide\" SID=\"Celeste/6-Reflection\" />\r\n  <RespawnPoint>\r\n    <X>10968</X>\r\n    <Y>4960</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/music/remix/06_reflection\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience Event=\"event:/env/amb/06_main\">\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>1</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>true</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags>\r\n    <string>StopFastRestartFlag</string>\r\n    <string>SpeedrunTool_SavedSate</string>\r\n  </Flags>\r\n  <LevelFlags>\r\n    <string>d-00</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters />\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"6\" Cassette=\"false\" SID=\"Celeste/6-Reflection\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"2\" TimePlayed=\"3842340000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>00</string>\r\n          <string>04</string>\r\n          <string>b-00</string>\r\n          <string>boss-00</string>\r\n          <string>after-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"true\" FullClear=\"false\" Deaths=\"558\" TimePlayed=\"61949020000\" BestTime=\"2787150000\" BestFullClearTime=\"0\" BestDashes=\"236\" BestDeaths=\"6\" HeartGem=\"true\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-00</string>\r\n          <string>d-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>d-00</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}