{
  "version": 3,
  "createdUtc": "2026-08-08T13:16:06.9891656Z",
  "start": {
    "areaSid": "Celeste/6-Reflection",
    "areaMode": "BSide",
    "level": "c-04",
    "respawnX": 10780,
    "respawnY": 4662
  },
  "inputs": [
    "40,R,D",
    "10,R,D,X",
    "1,D,X",
    "27,D",
    "12,R,D",
    "7,L,D",
    "47,L",
    "9,L,X",
    "13,L",
    "2,L,U",
    "8,L,U,X",
    "31,L,U",
    "1,F,270,1",
    "68,F,90,1",
    "10,F,135,1",
    "12,F,180,1",
    "12,F,225,1",
    "35,F,270,1",
    "6,F,225,1",
    "3,F,180,1",
    "30,D",
    "14,R,X",
    "17,R",
    "1,R,Z",
    "11,R,Z,G",
    "11,R,J,G",
    "3,R,G",
    "8,R",
    "1,R,U",
    "10,R,U,X",
    "11,R,U",
    "37,R",
    "9,R,X",
    "5,R",
    "10,R,S",
    "152,R",
    "9",
    "25,R",
    "6,R,S"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"c-04\" Time=\"1888190000\" StartedFromBeginning=\"false\" Deaths=\"69\" Dashes=\"6\" DashesAtLevelStart=\"6\" DeathsInCurrentLevel=\"22\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" ColorGrade=\"reflection\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"6\" Mode=\"BSide\" SID=\"Celeste/6-Reflection\" />\r\n  <RespawnPoint>\r\n    <X>10780</X>\r\n    <Y>4662</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/music/remix/06_reflection\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience Event=\"event:/env/amb/06_main\">\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>1</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>true</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags>\r\n    <string>StopFastRestartFlag</string>\r\n    <string>SpeedrunTool_SavedSate</string>\r\n    <string>CelesteTAS_TAS_Was_Run</string>\r\n  </Flags>\r\n  <LevelFlags>\r\n    <string>c-01</string>\r\n    <string>c-02</string>\r\n    <string>c-04</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters />\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"6\" Cassette=\"false\" SID=\"Celeste/6-Reflection\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"2\" TimePlayed=\"3842340000\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>00</string>\r\n          <string>04</string>\r\n          <string>b-00</string>\r\n          <string>boss-00</string>\r\n          <string>after-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"true\" FullClear=\"false\" Deaths=\"723\" TimePlayed=\"68301920000\" BestTime=\"2787150000\" BestFullClearTime=\"0\" BestDashes=\"236\" BestDeaths=\"6\" HeartGem=\"true\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>b-00</string>\r\n          <string>c-00</string>\r\n          <string>d-00</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>c-04</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}