{
  "version": 3,
  "createdUtc": "2026-09-23T10:53:58.3512891Z",
  "start": {
    "areaSid": "Celeste/LostLevels",
    "areaMode": "Normal",
    "level": "f-06",
    "respawnX": 23728,
    "respawnY": -6784
  },
  "inputs": [
    "25",
    "1,D",
    "10,R,D",
    "11,R,D,X",
    "3,R,D",
    "12,R,D,X",
    "2,R",
    "13,R,U,X",
    "23",
    "2,Z",
    "8,R,Z",
    "4,R,J",
    "9,R,J,Z",
    "1,L,J,Z",
    "68,L,J",
    "1,L,J,Z,G",
    "9,L,U,J,Z,G",
    "32,L,U,J,G",
    "4,L,U,G",
    "10,L,U,J,G",
    "1,L,J,G",
    "10,L,K,G",
    "12,L,J,G",
    "1,L,J",
    "9,L",
    "6",
    "6,R,J",
    "15,R",
    "3",
    "2,X",
    "4,L,X",
    "5,L",
    "13",
    "6,L",
    "12",
    "6,R",
    "18",
    "6,L,G",
    "6,G",
    "6,D,G",
    "13,G",
    "67,R,G",
    "10,R,J,G",
    "1,R,J,X,G",
    "7,L,U,J,X,G",
    "4,L,U,X,G",
    "1,L,U,G",
    "4,L,U,J,G",
    "2,R,U,J,G",
    "7,R,U,K,G",
    "16,R,U,K",
    "6,U,K",
    "11,U,K,X",
    "1,U,X",
    "2,X",
    "256",
    "5,J"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"f-06\" Time=\"194820000\" StartedFromBeginning=\"false\" Deaths=\"4\" Dashes=\"2\" DashesAtLevelStart=\"2\" DeathsInCurrentLevel=\"4\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" ColorGrade=\"none\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"10\" Mode=\"Normal\" SID=\"Celeste/LostLevels\" />\r\n  <RespawnPoint>\r\n    <X>23728</X>\r\n    <Y>-6784</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/new_content/music/lvl10/part03\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience Event=\"event:/env/amb/00_prologue\">\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>2</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>false</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags />\r\n  <LevelFlags>\r\n    <string>f-06</string>\r\n    <string>f-05</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters>\r\n    <Counter key=\"blackhole_strength\" value=\"0\" />\r\n  </Counters>\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"10\" Cassette=\"false\" SID=\"Celeste/LostLevels\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"true\" FullClear=\"false\" Deaths=\"533\" TimePlayed=\"113849340000\" BestTime=\"9439760000\" BestFullClearTime=\"0\" BestDashes=\"971\" BestDeaths=\"20\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>a-00</string>\r\n          <string>c-00</string>\r\n          <string>e-00z</string>\r\n          <string>f-door</string>\r\n          <string>h-00b</string>\r\n          <string>i-00</string>\r\n          <string>j-00</string>\r\n          <string>j-16</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>f-05</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}