{
  "version": 3,
  "createdUtc": "2026-09-21T04:39:55.970973Z",
  "start": {
    "areaSid": "Celeste/LostLevels",
    "areaMode": "Normal",
    "level": "f-07",
    "respawnX": 25504,
    "respawnY": -6704
  },
  "inputs": [
    "36",
    "2,L",
    "11,L,Z",
    "3,L",
    "19,L,J",
    "12,L",
    "17,L,X",
    "7,L",
    "14,L,X",
    "4,L,X,G",
    "7,L,U,X,G",
    "3,L,U,G",
    "4,U,G",
    "14,R,U,G",
    "15,R,G",
    "8,R,J,G",
    "13,R,G",
    "4,R",
    "1,L,D",
    "9,L,D,X",
    "2,L,X",
    "2,L",
    "10,L,J",
    "4,L",
    "12",
    "2,L",
    "1,L,G",
    "10,L,X,G",
    "12,L,G",
    "16,G",
    "43,U,G",
    "31,G"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"f-07\" Time=\"150960000\" StartedFromBeginning=\"false\" Deaths=\"3\" Dashes=\"3\" DashesAtLevelStart=\"3\" DeathsInCurrentLevel=\"3\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" ColorGrade=\"none\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"10\" Mode=\"Normal\" SID=\"Celeste/LostLevels\" />\r\n  <RespawnPoint>\r\n    <X>25504</X>\r\n    <Y>-6704</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/new_content/music/lvl10/part03\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience Event=\"event:/env/amb/00_prologue\">\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>2</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>false</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags />\r\n  <LevelFlags>\r\n    <string>f-07</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters>\r\n    <Counter key=\"blackhole_strength\" value=\"0\" />\r\n  </Counters>\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"10\" Cassette=\"false\" SID=\"Celeste/LostLevels\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"true\" FullClear=\"false\" Deaths=\"334\" TimePlayed=\"59259280000\" BestTime=\"9439760000\" BestFullClearTime=\"0\" BestDashes=\"971\" BestDeaths=\"20\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>a-00</string>\r\n          <string>c-00</string>\r\n          <string>e-00z</string>\r\n          <string>f-door</string>\r\n          <string>h-00b</string>\r\n          <string>i-00</string>\r\n          <string>j-00</string>\r\n          <string>j-16</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>f-07</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}