{
  "version": 3,
  "createdUtc": "2026-09-22T05:18:07.7787452Z",
  "start": {
    "areaSid": "Celeste/LostLevels",
    "areaMode": "Normal",
    "level": "e-08",
    "respawnX": 18480,
    "respawnY": -6176
  },
  "inputs": [
    "75",
    "12,L",
    "4,L,J",
    "20,L",
    "1",
    "8,R,X",
    "2,R",
    "1,R,J",
    "3,R,U,J",
    "10,R,U,J,X",
    "5,R,U,J",
    "15,R,U,J,X",
    "6,R,U,J",
    "4,R,U",
    "1,R",
    "5",
    "3,S",
    "1,D,S,O",
    "2,S",
    "38",
    "1,D",
    "2,R,D",
    "9,R,D,X",
    "3,R",
    "8,R,J",
    "6,R",
    "1,R,D,X",
    "7,R,D,X,G",
    "1,R,D,G",
    "2,R,G",
    "12,R,J,G",
    "1,R,U,J,G",
    "10,R,U,J,X,G",
    "7,R,G",
    "416"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"e-08\" Time=\"123250000\" StartedFromBeginning=\"false\" Deaths=\"2\" Dashes=\"5\" DashesAtLevelStart=\"5\" DeathsInCurrentLevel=\"2\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" ColorGrade=\"none\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"true\">\r\n  <Area ID=\"10\" Mode=\"Normal\" SID=\"Celeste/LostLevels\" />\r\n  <RespawnPoint>\r\n    <X>18480</X>\r\n    <Y>-6176</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/new_content/music/lvl10/intermission_heartgroove\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"progress\" Value=\"3\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience Event=\"event:/env/amb/00_prologue\">\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>2</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>false</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags />\r\n  <LevelFlags>\r\n    <string>e-08</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters>\r\n    <Counter key=\"blackhole_strength\" value=\"0\" />\r\n  </Counters>\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"10\" Cassette=\"false\" SID=\"Celeste/LostLevels\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"true\" FullClear=\"false\" Deaths=\"372\" TimePlayed=\"62350730000\" BestTime=\"9439760000\" BestFullClearTime=\"0\" BestDashes=\"971\" BestDeaths=\"20\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>a-00</string>\r\n          <string>c-00</string>\r\n          <string>e-00z</string>\r\n          <string>f-door</string>\r\n          <string>h-00b</string>\r\n          <string>i-00</string>\r\n          <string>j-00</string>\r\n          <string>j-16</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>e-08</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}