{
  "version": 3,
  "createdUtc": "2026-09-23T11:18:12.5700011Z",
  "start": {
    "areaSid": "Celeste/LostLevels",
    "areaMode": "Normal",
    "level": "j-11",
    "respawnX": 66120,
    "respawnY": -10432
  },
  "inputs": [
    "35",
    "1,Z",
    "9,R,Z",
    "3,R",
    "23,R,J",
    "1,R,U,J,G",
    "14,R,U,J,X,G",
    "7,R,U,J,G",
    "127,R,U,G",
    "2,R,U,J,H",
    "20,R,U,K,H",
    "16,R,K,H",
    "12,R,K",
    "18,K",
    "12,L,K",
    "39,L",
    "10,L,X",
    "5,L",
    "2,L,D",
    "10,L,D,X",
    "6,L,D",
    "9,L,D,X",
    "5,L,D",
    "13,L,D,X",
    "2,L,D",
    "12",
    "1,U",
    "9,U,X",
    "2,X",
    "9",
    "2,D",
    "10,L,D,X",
    "5,L,D",
    "11,L,D,X",
    "3,L,D",
    "12,L,D,X",
    "2,L,D",
    "47",
    "13,R",
    "9",
    "2,L",
    "11,L,X",
    "7,L",
    "1,L,D",
    "10,L,D,X",
    "3,L,D",
    "14,L,D,X",
    "2,L,D",
    "19",
    "8,U,X",
    "1,X",
    "52"
  ],
  "sessionXml": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Session xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Level=\"j-11\" Time=\"0\" StartedFromBeginning=\"false\" Deaths=\"0\" Dashes=\"0\" DashesAtLevelStart=\"0\" DeathsInCurrentLevel=\"0\" InArea=\"true\" FirstLevel=\"false\" Cassette=\"false\" HeartGem=\"false\" Dreaming=\"false\" ColorGrade=\"none\" LightingAlphaAdd=\"0\" BloomBaseAdd=\"0\" DarkRoomAlpha=\"0.75\" CoreMode=\"None\" GrabbedGolden=\"false\" HitCheckpoint=\"false\">\r\n  <Area ID=\"10\" Mode=\"Normal\" SID=\"Celeste/LostLevels\" />\r\n  <RespawnPoint>\r\n    <X>66120</X>\r\n    <Y>-10432</Y>\r\n  </RespawnPoint>\r\n  <Audio>\r\n    <Music Event=\"event:/new_content/music/lvl10/final_run\">\r\n      <Parameters>\r\n        <MEP Key=\"layer1\" Value=\"1\" />\r\n        <MEP Key=\"layer2\" Value=\"1\" />\r\n        <MEP Key=\"layer3\" Value=\"1\" />\r\n        <MEP Key=\"layer4\" Value=\"1\" />\r\n        <MEP Key=\"progress\" Value=\"2\" />\r\n        <MEP Key=\"layer6\" Value=\"0\" />\r\n      </Parameters>\r\n    </Music>\r\n    <Ambience Event=\"event:/env/amb/00_prologue\">\r\n      <Parameters />\r\n    </Ambience>\r\n    <AmbienceVolume xsi:nil=\"true\" />\r\n  </Audio>\r\n  <Inventory>\r\n    <Dashes>1</Dashes>\r\n    <DreamDash>true</DreamDash>\r\n    <Backpack>false</Backpack>\r\n    <NoRefills>false</NoRefills>\r\n  </Inventory>\r\n  <Flags />\r\n  <LevelFlags>\r\n    <string>j-11</string>\r\n  </LevelFlags>\r\n  <Strawberries />\r\n  <DoNotLoad />\r\n  <Keys />\r\n  <Counters />\r\n  <SummitGems>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n    <boolean>false</boolean>\r\n  </SummitGems>\r\n  <OldStats ID=\"10\" Cassette=\"false\" SID=\"Celeste/LostLevels\">\r\n    <Modes>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"true\" SingleRunCompleted=\"true\" FullClear=\"false\" Deaths=\"657\" TimePlayed=\"123855880000\" BestTime=\"9439760000\" BestFullClearTime=\"0\" BestDashes=\"971\" BestDeaths=\"20\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints>\r\n          <string>a-00</string>\r\n          <string>c-00</string>\r\n          <string>e-00z</string>\r\n          <string>f-door</string>\r\n          <string>h-00b</string>\r\n          <string>i-00</string>\r\n          <string>j-00</string>\r\n          <string>j-16</string>\r\n        </Checkpoints>\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n      <AreaModeStats TotalStrawberries=\"0\" Completed=\"false\" SingleRunCompleted=\"false\" FullClear=\"false\" Deaths=\"0\" TimePlayed=\"0\" BestTime=\"0\" BestFullClearTime=\"0\" BestDashes=\"0\" BestDeaths=\"0\" HeartGem=\"false\">\r\n        <Strawberries />\r\n        <Checkpoints />\r\n      </AreaModeStats>\r\n    </Modes>\r\n  </OldStats>\r\n  <UnlockedCSide>false</UnlockedCSide>\r\n  <FurthestSeenLevel>j-11</FurthestSeenLevel>\r\n  <BeatBestTime>false</BeatBestTime>\r\n  <RestartedFromGolden>false</RestartedFromGolden>\r\n  <Sliders />\r\n</Session>"
}